#pragma once

#ifndef WIFI_SSID
#define WIFI_SSID "YOUR_WIFI_SSID"
#endif

#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#endif

#define APP_LOCATION_NAME "COQUITLAM, BC"
#define APP_LATITUDE "49.266667"
#define APP_LONGITUDE "-122.78333"

#define WEATHER_UPDATE_INTERVAL_MS (20 * 60 * 1000)
#define WEATHER_RETRY_INTERVAL_MS (2 * 60 * 1000)
#define WEATHER_STALE_AFTER_SEC (45 * 60)

#define WIFI_CONNECT_TIMEOUT_MS 30000
#define WIFI_RETRY_INTERVAL_MS 10000

#define NTP_SERVER_PRIMARY "pool.ntp.org"
#define NTP_SERVER_SECONDARY "time.google.com"
